# Cloudflare Workers 配置文件
name = "mastra-weather-app"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# 环境变量
[vars]
APP_NAME = "Mastra Weather App"
APP_VERSION = "1.0.0"
ENVIRONMENT = "production"

# 开发环境配置
[env.dev]
name = "mastra-weather-app-dev"
vars = { ENVIRONMENT = "development" }
